import fs from 'fs';
let content = fs.readFileSync('src/translations.tsx', 'utf-8');

// English
content = content.replace(
`        content: (contract: any) => <div className="space-y-2"><p>6.1 In the event that the vehicle subject to the rental is slightly damaged or seriously damaged due to negligent use or fault of Party (B), the repair shall be the responsibility of Party (B), except in the case of wear and tear due to normal use, in which case the repair shall be the responsibility of Party (A).</p><p>6.2 Party (B) shall be fully responsible for any damage to the vehicle such as (collision, overturning, falling into water, theft, fire or other accidents) by paying compensation as agreed upon at a price of <span className="font-bold">{contract.carCompensation ? contract.carCompensation : '_______________________'}</span> of the vehicle price to Party (A).</p><p>6.3 In the event that Party (B) uses the vehicle with collisions, scratches or other damages, Party (A) must be notified without allowing Party (B) to conceal the information of taking the vehicle for repair without the consent of Party (A).</p></div>`,
`        content: (contract: any) => <div className="space-y-2"><p>6.1 In the event that the vehicle subject to the rental is slightly damaged or seriously damaged due to negligent use or fault of Party (B), the repair shall be the responsibility of Party (B), except in the case of wear and tear due to normal use, in which case the repair shall be the responsibility of Party (A).</p><p>6.2 Party (B) shall be fully responsible for any damage to the vehicle such as (collision, overturning, falling into water, theft, fire or other accidents) by paying compensation as agreed upon at a price of <span className="font-bold">{contract.carCompensation ? contract.carCompensation : '_______________________'}</span> of the vehicle price to Party (A).</p><p>6.3 In the event that Party (B) uses the vehicle with collisions, scratches or other damages, Party (A) must be notified without allowing Party (B) to conceal the information of taking the vehicle for repair without the consent of Party (A).</p><p>6.4 Maintenance and replacement of parts that have reached the end of their lifespan or are damaged by normal use is the responsibility of Party (A).</p></div>`
);

// Japanese
content = content.replace(
`        content: (contract: any) => <div className="space-y-2"><p>6.1 賃貸対象の車両が乙(B)の過失または責任により軽微または深刻な損傷を受けた場合、修理の責任は乙(B)が負うものとする。ただし、通常の使用による摩耗や劣化の場合の修理は甲(A)の責任とする。</p><p>6.2 乙(B)は、合意された車両価格の <span className="font-bold">{contract.carCompensation ? contract.carCompensation : '_______________________'}</span> に相当する賠償金を甲(A)に支払うことにより、車両へのあらゆる損害（衝突、横転、水没、盗難、火災、その他の事故など）に対して全責任を負うものとする。</p><p>6.3 衝突、傷、その他の損傷がある状態で乙(B)が車両を使用する場合、甲(A)に通知しなければならず、乙(B)が甲(A)の同意なしに車両を修理に出した情報を隠蔽することは許されない。</p></div>`,
`        content: (contract: any) => <div className="space-y-2"><p>6.1 賃貸対象の車両が乙(B)の過失または責任により軽微または深刻な損傷を受けた場合、修理の責任は乙(B)が負うものとする。ただし、通常の使用による摩耗や劣化の場合の修理は甲(A)の責任とする。</p><p>6.2 乙(B)は、合意された車両価格の <span className="font-bold">{contract.carCompensation ? contract.carCompensation : '_______________________'}</span> に相当する賠償金を甲(A)に支払うことにより、車両へのあらゆる損害（衝突、横転、水没、盗難、火災、その他の事故など）に対して全責任を負うものとする。</p><p>6.3 衝突、傷、その他の損傷がある状態で乙(B)が車両を使用する場合、甲(A)に通知しなければならず、乙(B)が甲(A)の同意なしに車両を修理に出した情報を隠蔽することは許されない。</p><p>6.4 寿命に達した部品または通常の使用により損傷した部品のメンテナンスおよび交換は甲(A)の責任とする。</p></div>`
);

// Korean
content = content.replace(
`        content: (contract: any) => <div className="space-y-2"><p>6.1 임대 대상 차량이 을(B)의 부주의한 사용이나 과실로 인해 경미하거나 심각한 손상을 입은 경우, 정상적인 사용으로 인한 마모 및 훼손의 경우는 갑(A)이 수리 책임을 지는 것을 제외하고는 을(B)이 수리 책임을 져야 한다.</p><p>6.2 을(B)은 합의된 차량 가격의 <span className="font-bold">{contract.carCompensation ? contract.carCompensation : '_______________________'}</span>에 해당하는 보상금을 갑(A)에게 지불함으로써 (충돌, 전복, 침수, 도난, 화재 또는 기타 사고) 등 차량의 모든 손상에 대해 전적인 책임을 져야 한다.</p><p>6.3 을(B)이 충돌, 긁힘 또는 기타 손상이 있는 상태로 차량을 사용하는 경우 갑(A)에게 통지해야 하며, 을(B)이 갑(A)의 동의 없이 차량을 수리한 사실을 숨겨서는 안 된다.</p></div>`,
`        content: (contract: any) => <div className="space-y-2"><p>6.1 임대 대상 차량이 을(B)의 부주의한 사용이나 과실로 인해 경미하거나 심각한 손상을 입은 경우, 정상적인 사용으로 인한 마모 및 훼손의 경우는 갑(A)이 수리 책임을 지는 것을 제외하고는 을(B)이 수리 책임을 져야 한다.</p><p>6.2 을(B)은 합의된 차량 가격의 <span className="font-bold">{contract.carCompensation ? contract.carCompensation : '_______________________'}</span>에 해당하는 보상금을 갑(A)에게 지불함으로써 (충돌, 전복, 침수, 도난, 화재 또는 기타 사고) 등 차량의 모든 손상에 대해 전적인 책임을 져야 한다.</p><p>6.3 을(B)이 충돌, 긁힘 또는 기타 손상이 있는 상태로 차량을 사용하는 경우 갑(A)에게 통지해야 하며, 을(B)이 갑(A)의 동의 없이 차량을 수리한 사실을 숨겨서는 안 된다.</p><p>6.4 수명이 다하거나 정상적인 사용으로 인해 손상된 부품의 유지보수 및 교체는 갑(A)의 책임이다.</p></div>`
);

// Russian
content = content.replace(
`        content: (contract: any) => <div className="space-y-2"><p>6.1 В случае если арендуемое транспортное средство получило легкие или серьезные повреждения из-за небрежного использования или по вине Стороны (B), ответственность за ремонт несет Сторона (B), за исключением случаев износа в результате нормального использования, когда ответственность за ремонт несет Сторона (A).</p><p>6.2 Сторона (B) несет полную ответственность за любой ущерб транспортному средству (столкновение, опрокидывание, падение в воду, кража, пожар или другие несчастные случаи), выплатив Стороне (A) согласованную компенсацию в размере <span className="font-bold">{contract.carCompensation ? contract.carCompensation : '_______________________'}</span> от стоимости автомобиля.</p><p>6.3 В случае если Сторона (B) использует автомобиль со следами столкновений, царапинами или другими повреждениями, Сторона (A) должна быть об этом уведомлена; Стороне (B) не разрешается скрывать информацию о передаче автомобиля в ремонт без согласия Стороны (A).</p></div>`,
`        content: (contract: any) => <div className="space-y-2"><p>6.1 В случае если арендуемое транспортное средство получило легкие или серьезные повреждения из-за небрежного использования или по вине Стороны (B), ответственность за ремонт несет Сторона (B), за исключением случаев износа в результате нормального использования, когда ответственность за ремонт несет Сторона (A).</p><p>6.2 Сторона (B) несет полную ответственность за любой ущерб транспортному средству (столкновение, опрокидывание, падение в воду, кража, пожар или другие несчастные случаи), выплатив Стороне (A) согласованную компенсацию в размере <span className="font-bold">{contract.carCompensation ? contract.carCompensation : '_______________________'}</span> от стоимости автомобиля.</p><p>6.3 В случае если Сторона (B) использует автомобиль со следами столкновений, царапинами или другими повреждениями, Сторона (A) должна быть об этом уведомлена; Стороне (B) не разрешается скрывать информацию о передаче автомобиля в ремонт без согласия Стороны (A).</p><p>6.4 Обслуживание и замена деталей, срок службы которых истек или которые повреждены в результате нормального использования, является обязанностью Стороны (A).</p></div>`
);

// Fix English Article 7 -> Article 6: VEHICLE DAMAGE CASE
content = content.replace(/title: "Article 7: VEHICLE DAMAGE CASE",/g, 'title: "Article 6: VEHICLE DAMAGE CASE",');
// Fix Japanese 第7条: 車両破損時の対応 -> 第6条: 車両破損時の対応
content = content.replace(/title: "第7条: 車両破損時の対応",/g, 'title: "第6条: 車両破損時の対応",');


fs.writeFileSync('src/translations.tsx', content);
